-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZIaZFkzTYxjbupBM
S+ETPrip9xncQVVtXZI/s7zYj4igCgYIKoZIzj0DAQehRANCAAT/XcNXhpuowG4G
glTO8h3CkBMIo9Tm6p8Ruq0DdTlDAks1JPBFJk3CAWvFIstBYLfs8XvUymvYHr/i
0KxGC0iK
-----END PRIVATE KEY-----